In [29]:
with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE staging.stg_fda_shortages"))
    conn.execute(text("TRUNCATE TABLE core.fact_shortage"))
    conn.execute(text("DELETE FROM core.dim_drug"))
    conn.execute(text("DELETE FROM core.dim_manufacturer"))
print("✅ All cleared")

✅ All cleared

In [30]:
pip install requests pandas sqlalchemy pyodbc beautifulsoup4 python-dotenv jupyter openpyxl rapidfuzz

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.39)
Requirement already satisfied: pyodbc in c:\programdata\anaconda3\lib\site-packages (5.2.0)
Requirement already satisfied: beautifulsoup4 in c:\programdata\anaconda3\lib\site-packages (4.12.3)
Requirement already satisfied: python-dotenv in c:\programdata\anaconda3\lib\site-packages (1.1.0)
Requirement already satisfied: jupyter in c:\programdata\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: openpyxl in c:\programdata\anaconda3\lib\site-packages (3.1.5)
Requirement already satisfied: rapidfuzz in c:\users\mayur rane\appdata\roaming\python\python313\site-packages (3.14.5)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests) (2025.4.26)
Requirement already satisfied: numpy>=1.26.0 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\programdata\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: greenlet!=0.4.17 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.12.2)
Requirement already satisfied: soupsieve>1.2 in c:\programdata\anaconda3\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: notebook in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.3.2)
Requirement already satisfied: jupyter-console in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.6.3)
Requirement already satisfied: nbconvert in c:\programdata\anaconda3\lib\site-packages (from jupyter) (7.16.6)
Requirement already satisfied: ipykernel in c:\programdata\anaconda3\lib\site-packages (from jupyter) (6.29.5)
Requirement already satisfied: ipywidgets in c:\programdata\anaconda3\lib\site-packages (from jupyter) (8.1.5)
Requirement already satisfied: jupyterlab in c:\programdata\anaconda3\lib\site-packages (from jupyter) (4.3.4)
Requirement already satisfied: et-xmlfile in c:\programdata\anaconda3\lib\site-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.2.1)
Requirement already satisfied: debugpy>=1.6.5 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.8.11)
Requirement already satisfied: ipython>=7.23.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.30.0)
Requirement already satisfied: jupyter-client>=6.1.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (8.6.3)
Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.7.2)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (0.1.6)
Requirement already satisfied: nest-asyncio in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (1.6.0)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (24.2)
Requirement already satisfied: psutil in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.9.0)
Requirement already satisfied: pyzmq>=24 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (26.2.0)
Requirement already satisfied: tornado>=6.1 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (6.5.1)
Requirement already satisfied: traitlets>=5.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipykernel->jupyter) (5.14.3)
Requirement already satisfied: decorator in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.1.1)
Requirement already satisfied: jedi>=0.16 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.19.2)
Requirement already satisfied: prompt-toolkit<3.1.0,>=3.0.41 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.43)
Requirement already satisfied: pygments>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.19.1)
Requirement already satisfied: stack-data in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.2.0)
Requirement already satisfied: colorama in c:\programdata\anaconda3\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: wcwidth in c:\programdata\anaconda3\lib\site-packages (from prompt-toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.2.5)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\programdata\anaconda3\lib\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter) (0.8.4)
Requirement already satisfied: platformdirs>=2.5 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (4.3.7)
Requirement already satisfied: pywin32>=300 in c:\programdata\anaconda3\lib\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter) (308)
Requirement already satisfied: widgetsnbextension~=4.0.12 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (4.0.13)
Requirement already satisfied: jupyterlab_widgets~=3.0.12 in c:\programdata\anaconda3\lib\site-packages (from ipywidgets->jupyter) (3.0.13)
Requirement already satisfied: async-lru>=1.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.0.4)
Requirement already satisfied: httpx>=0.25.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.2.5)
Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.15.0)
Requirement already satisfied: jupyterlab-server<3,>=2.27.1 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (2.27.3)
Requirement already satisfied: notebook-shim>=0.2 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: setuptools>=40.8.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab->jupyter) (72.1.0)
Requirement already satisfied: anyio>=3.1.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (4.7.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.3.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.12.0)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.5.3)
Requirement already satisfied: nbformat>=5.3.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: overrides>=5.0 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (7.4.0)
Requirement already satisfied: prometheus-client>=0.9 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.21.1)
Requirement already satisfied: pywinpty>=2.0.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.0.15)
Requirement already satisfied: send2trash>=1.8.2 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.2)
Requirement already satisfied: terminado>=0.8.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.17.1)
Requirement already satisfied: websocket-client>=1.7 in c:\programdata\anaconda3\lib\site-packages (from jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.8.0)
Requirement already satisfied: babel>=2.10 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2.16.0)
Requirement already satisfied: json5>=0.9.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.9.25)
Requirement already satisfied: jsonschema>=4.18.0 in c:\programdata\anaconda3\lib\site-packages (from jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (4.23.0)
Requirement already satisfied: sniffio>=1.1 in c:\programdata\anaconda3\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: argon2-cffi-bindings in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (21.2.0)
Requirement already satisfied: httpcore==1.* in c:\programdata\anaconda3\lib\site-packages (from httpx>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\programdata\anaconda3\lib\site-packages (from httpcore==1.*->httpx>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\programdata\anaconda3\lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.2)
Requirement already satisfied: attrs>=22.2.0 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (24.3.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (2023.7.1)
Requirement already satisfied: referencing>=0.28.4 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.30.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\programdata\anaconda3\lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.27.1->jupyterlab->jupyter) (0.22.3)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (3.2.1)
Requirement already satisfied: pyyaml>=5.3 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (6.0.2)
Requirement already satisfied: rfc3339-validator in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\programdata\anaconda3\lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\users\mayur rane\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\users\mayur rane\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\programdata\anaconda3\lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.1)
Requirement already satisfied: uri-template in c:\users\mayur rane\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\users\mayur rane\appdata\roaming\python\python313\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: bleach!=5.0.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.2.0)
Requirement already satisfied: defusedxml in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (3.1.2)
Requirement already satisfied: nbclient>=0.5.0 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (0.10.2)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\programdata\anaconda3\lib\site-packages (from nbconvert->jupyter) (1.5.0)
Requirement already satisfied: webencodings in c:\programdata\anaconda3\lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2<1.5,>=1.1.0 in c:\programdata\anaconda3\lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.4.0)
Requirement already satisfied: fastjsonschema>=2.15 in c:\programdata\anaconda3\lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.20.0)
Requirement already satisfied: cffi>=1.0.1 in c:\programdata\anaconda3\lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\programdata\anaconda3\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (2.21)
Requirement already satisfied: arrow>=0.15.0 in c:\programdata\anaconda3\lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.4.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: executing in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.8.3)
Requirement already satisfied: asttokens in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (3.0.0)
Requirement already satisfied: pure-eval in c:\programdata\anaconda3\lib\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter) (0.2.2)
Note: you may need to restart the kernel to use updated packages.

In [31]:
import pyodbc

In [32]:
print(pyodbc.drivers())

['SQL Server', 'SQL Server Native Client 11.0', 'ODBC Driver 11 for SQL Server', 'SQL Server Native Client RDA 11.0', 'ODBC Driver 17 for SQL Server', 'ODBC Driver 18 for SQL Server', 'Microsoft Access Driver (*.mdb, *.accdb)', 'Microsoft Excel Driver (*.xls, *.xlsx, *.xlsm, *.xlsb)', 'Microsoft Access Text Driver (*.txt, *.csv)', 'Microsoft Access dBASE Driver (*.dbf, *.ndx, *.mdx)']

In [33]:
# CELL 1 — Imports
import requests
import pandas as pd
import json
import hashlib
from sqlalchemy import create_engine, text
from datetime import datetime
import warnings
warnings.filterwarnings('ignore')

print("✅ Libraries loaded")

✅ Libraries loaded

In [34]:
# CELL 2 — Connect to SQL Server
# Windows Authentication (recommended — no password needed)
engine = create_engine(
    "mssql+pyodbc://@LAPTOP-K44AI2HU\\SQLEXPRESS/pharma_db"
    "?driver=ODBC+Driver+17+for+SQL+Server"
    "&trusted_connection=yes"
)

# Alternative: SQL Server Authentication (if you set SA password)
# engine = create_engine(
#     "mssql+pyodbc://sa:YourPassword@localhost/pharma_db"
#     "?driver=ODBC+Driver+17+for+SQL+Server"
# )

with engine.connect() as conn:
    result = conn.execute(text("SELECT DB_NAME()"))
    print(f"✅ Connected to: {result.fetchone()[0]}")

✅ Connected to: pharma_db

In [35]:
# CELL 3 — Fetch FDA data
def fetch_fda_shortages(limit=100):
    url = "https://api.fda.gov/drug/shortages.json"
    all_records = []
    skip = 0

    while True:
        params = {"limit":100, "skip": skip}
        try: 
            resp = requests.get(url, params=params, timeout=30)
            resp.raise_for_status()
            data = resp.json()
            results = data.get("results", [])
            if not results:
                break
            all_records.extend(results)
            total = data.get("meta", {}).get("results", {}).get("total", 0)
            print(f"  Fetched {len(all_records)}/{total} records...")
            if limit is not None and len(all_records) >= min(total, limit):
                break
            skip += 100
        except Exception as e:
            print(f"  Error: {e}")
            break

    return all_records

print("Fetching FDA drug shortage data...")
records = fetch_fda_shortages(limit= None)
print(f"\n✅ Total records fetched: {len(records)}")

Fetching FDA drug shortage data...
  Fetched 100/1670 records...
  Fetched 200/1670 records...
  Fetched 300/1670 records...
  Fetched 400/1670 records...
  Fetched 500/1670 records...
  Fetched 600/1670 records...
  Fetched 700/1670 records...
  Fetched 800/1670 records...
  Fetched 900/1670 records...
  Fetched 1000/1670 records...
  Fetched 1100/1670 records...
  Fetched 1200/1670 records...
  Fetched 1300/1670 records...
  Fetched 1400/1670 records...
  Fetched 1500/1670 records...
  Fetched 1600/1670 records...
  Fetched 1670/1670 records...
  Error: 404 Client Error: Not Found for url: https://api.fda.gov/drug/shortages.json?limit=100&skip=1700

✅ Total records fetched: 1670

In [36]:
# CELL 4 — Convert to DataFrame and preview
def normalize_fda(records):
    rows = []
    for r in records:
        # therapeutic_category is a list — grab first item
        tc = r.get("therapeutic_category", [])
        category = tc[0] if isinstance(tc, list) and tc else str(tc) if tc else "UNCATEGORIZED"

        rows.append({
            "source_id":      r.get("id", ""),
            "drug_name":      r.get("generic_name", "").strip().upper() if r.get("generic_name") else "",
            "brand_name":     r.get("openfda", {}).get("brand_name", [""])[0],
            "manufacturer":   r.get("company_name", ""),
            "status":         r.get("status", "UNKNOWN").upper(),
            "reason":         r.get("shortage_reason", ""),       # ← fixed field name
            "presentation":   r.get("presentation", ""),
            "shortage_start": r.get("initial_posting_date", ""),  # ← actual date field
            "shortage_end":   r.get("update_date", ""),           # ← actual date field
            "therapeutic_category": category,                      # ← new field
            "source":         "FDA",
            "raw_json":       json.dumps(r),
            "ingested_at":    datetime.utcnow(),
        })
    return pd.DataFrame(rows)

df = normalize_fda(records)
print(f"DataFrame shape: {df.shape}")
df.head(3)

DataFrame shape: (1670, 13)

,source_id,drug_name,brand_name,manufacturer,status,reason,presentation,shortage_start,shortage_end,therapeutic_category,source,raw_json,ingested_at
0,,QUINAPRIL HYDROCHLORIDE TABLET,QUINAPRIL,"Solco Healthcare US, LLC",CURRENT,Shortage of an active ingredient,"Quinapril Hydrochloride, Tablet, 10 mg (NDC 43...",01/19/2023,04/29/2026,Cardiovascular,FDA,"{""update_type"": ""Reverified"", ""initial_posting...",2026-06-05 05:01:30.087963
1,,EVEROLIMUS TABLET,EVEROLIMUS,"Teva Pharmaceuticals USA, Inc.",TO BE DISCONTINUED,,"Everolimus, Tablet, 7.5 mg (NDC 0093-7768-24)",03/02/2026,03/02/2026,Transplant,FDA,"{""discontinued_date"": ""03/02/2026"", ""update_ty...",2026-06-05 05:01:30.087998
2,,PILOCARPINE HYDROCHLORIDE TABLET,PILOCARPINE HYDROCHLORIDE,"Actavis Pharma, Inc.",TO BE DISCONTINUED,,"Salagen, Tablet, 7.5 mg (NDC 0228-2837-11)",09/19/2025,09/19/2025,Other,FDA,"{""discontinued_date"": ""09/19/2025"", ""update_ty...",2026-06-05 05:01:30.088017

In [37]:
df = df.drop(columns=["json_len"], errors="ignore")

In [38]:
with engine.begin() as conn:
    conn.execute(text("TRUNCATE TABLE staging.stg_fda_shortages"))

In [39]:
df

,source_id,drug_name,brand_name,manufacturer,status,reason,presentation,shortage_start,shortage_end,therapeutic_category,source,raw_json,ingested_at
0,,QUINAPRIL HYDROCHLORIDE TABLET,QUINAPRIL,"Solco Healthcare US, LLC",CURRENT,Shortage of an active ingredient,"Quinapril Hydrochloride, Tablet, 10 mg (NDC 43...",01/19/2023,04/29/2026,Cardiovascular,FDA,"{""update_type"": ""Reverified"", ""initial_posting...",2026-06-05 05:01:30.087963
1,,EVEROLIMUS TABLET,EVEROLIMUS,"Teva Pharmaceuticals USA, Inc.",TO BE DISCONTINUED,,"Everolimus, Tablet, 7.5 mg (NDC 0093-7768-24)",03/02/2026,03/02/2026,Transplant,FDA,"{""discontinued_date"": ""03/02/2026"", ""update_ty...",2026-06-05 05:01:30.087998
2,,PILOCARPINE HYDROCHLORIDE TABLET,PILOCARPINE HYDROCHLORIDE,"Actavis Pharma, Inc.",TO BE DISCONTINUED,,"Salagen, Tablet, 7.5 mg (NDC 0228-2837-11)",09/19/2025,09/19/2025,Other,FDA,"{""discontinued_date"": ""09/19/2025"", ""update_ty...",2026-06-05 05:01:30.088017
3,,ETOMIDATE INJECTION,AMIDATE,"Hospira, Inc., a Pfizer Company",CURRENT,Other,"Amidate, Injection, 2 mg/mL (NDC 0409-6695-02)",10/05/2022,05/22/2026,Anesthesia,FDA,"{""update_type"": ""Revised"", ""initial_posting_da...",2026-06-05 05:01:30.088037
4,,OMEPRAZOLE DELAYED RELEASE CAPSULE,OMEPRAZOLE,Sandoz Inc.,TO BE DISCONTINUED,,"Omeprazole, Delayed Release Capsule, 10 mg (ND...",10/09/2025,10/09/2025,Gastroenterology,FDA,"{""discontinued_date"": ""10/09/2025"", ""update_ty...",2026-06-05 05:01:30.088059
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1665,,FINASTERIDE TABLET,FINASTERIDE,"Teva Pharmaceuticals USA, Inc.",TO BE DISCONTINUED,,"Finasteride, Tablet, 5 mg (NDC 0093-7355-05)",08/19/2025,08/19/2025,Urology,FDA,"{""discontinued_date"": ""08/19/2025"", ""update_ty...",2026-06-05 05:01:30.115501
1666,,RAMELTEON TABLET,ROZEREM,Takeda Pharmaceuticals USA Inc.,TO BE DISCONTINUED,,"Rozerem, Tablet, 8 mg (NDC 64764-805-30)",03/19/2026,03/19/2026,Psychiatry,FDA,"{""discontinued_date"": ""03/19/2026"", ""update_ty...",2026-06-05 05:01:30.115514
1667,,"FLUVASTATIN SODIUM TABLET, EXTENDED RELEASE",LESCOL XL,Sandoz Inc.,TO BE DISCONTINUED,,"Lescol XL, Tablet, Extended Release, 80 mg (ND...",01/27/2026,01/27/2026,Cardiovascular,FDA,"{""discontinued_date"": ""01/27/2026"", ""update_ty...",2026-06-05 05:01:30.115528
1668,,"AMPHETAMINE ASPARTATE MONOHYDRATE, AMPHETAMINE...","DEXTROAMPHETAMINE SACCHARATE, AMPHETAMINE ASPA...","Teva Pharmaceuticals USA, Inc.",CURRENT,Other,"Amphetamine Aspartate Monohydrate, Amphetamine...",10/12/2022,06/02/2026,Psychiatry,FDA,"{""update_type"": ""Revised"", ""initial_posting_da...",2026-06-05 05:01:30.115544
1669,,LIDOCAINE HYDROCHLORIDE INJECTION,LIDOCAINE HYDROCHLORIDE,"Hospira, Inc., a Pfizer Company",CURRENT,,"Lidocaine Hydrochloride Preservative Free, Inj...",02/22/2012,05/22/2026,Anesthesia,FDA,"{""update_type"": ""Reverified"", ""initial_posting...",2026-06-05 05:01:30.115561

In [40]:

df.to_sql(
    "stg_fda_shortages",
    engine,
    schema="staging",
    if_exists="append",
    index=False,
    chunksize=100
)

print(f"✅ Loaded {len(df)} rows")

✅ Loaded 1670 rows

In [41]:
# CELL 6 — Verify in database
with engine.connect() as conn:
    count = conn.execute(text("SELECT COUNT(*) FROM staging.stg_fda_shortages")).fetchone()[0]
    print(f"✅ Records in staging table: {count}")

    # Preview — SQL Server uses TOP instead of LIMIT
    sample = pd.read_sql(
        "SELECT TOP 5 shortage_start FROM staging.stg_fda_shortages",
        engine
    )
    print("\nSample data:")
    print(sample.to_string())

✅ Records in staging table: 1670

Sample data:
  shortage_start
0     01/19/2023
1     03/02/2026
2     09/19/2025
3     10/05/2022
4     10/09/2025

In [42]:
df = normalize_fda(records)
print(df)

     source_id                                          drug_name  \
0                                  QUINAPRIL HYDROCHLORIDE TABLET
1                                               EVEROLIMUS TABLET
2                                PILOCARPINE HYDROCHLORIDE TABLET
3                                             ETOMIDATE INJECTION
4                              OMEPRAZOLE DELAYED RELEASE CAPSULE
...        ...                                                ...
1665                                           FINASTERIDE TABLET
1666                                             RAMELTEON TABLET
1667                  FLUVASTATIN SODIUM TABLET, EXTENDED RELEASE
1668            AMPHETAMINE ASPARTATE MONOHYDRATE, AMPHETAMINE...
1669                            LIDOCAINE HYDROCHLORIDE INJECTION

                                             brand_name  \
0                                             QUINAPRIL
1                                            EVEROLIMUS
2                             PILOCARPINE HYDROCHLORIDE
3                                               AMIDATE
4                                            OMEPRAZOLE
...                                                 ...
1665                                        FINASTERIDE
1666                                            ROZEREM
1667                                          LESCOL XL
1668  DEXTROAMPHETAMINE SACCHARATE, AMPHETAMINE ASPA...
1669                            LIDOCAINE HYDROCHLORIDE

                         manufacturer              status  \
0            Solco Healthcare US, LLC             CURRENT
1      Teva Pharmaceuticals USA, Inc.  TO BE DISCONTINUED
2                Actavis Pharma, Inc.  TO BE DISCONTINUED
3     Hospira, Inc., a Pfizer Company             CURRENT
4                         Sandoz Inc.  TO BE DISCONTINUED
...                               ...                 ...
1665   Teva Pharmaceuticals USA, Inc.  TO BE DISCONTINUED
1666  Takeda Pharmaceuticals USA Inc.  TO BE DISCONTINUED
1667                      Sandoz Inc.  TO BE DISCONTINUED
1668   Teva Pharmaceuticals USA, Inc.             CURRENT
1669  Hospira, Inc., a Pfizer Company             CURRENT

                                reason  \
0     Shortage of an active ingredient
1
2
3                                Other
4
...                                ...
1665
1666
1667
1668                             Other
1669

                                           presentation shortage_start  \
0     Quinapril Hydrochloride, Tablet, 10 mg (NDC 43...     01/19/2023
1         Everolimus, Tablet, 7.5 mg (NDC 0093-7768-24)     03/02/2026
2            Salagen, Tablet, 7.5 mg (NDC 0228-2837-11)     09/19/2025
3        Amidate, Injection, 2 mg/mL (NDC 0409-6695-02)     10/05/2022
4     Omeprazole, Delayed Release Capsule, 10 mg (ND...     10/09/2025
...                                                 ...            ...
1665       Finasteride, Tablet, 5 mg (NDC 0093-7355-05)     08/19/2025
1666           Rozerem, Tablet, 8 mg (NDC 64764-805-30)     03/19/2026
1667  Lescol XL, Tablet, Extended Release, 80 mg (ND...     01/27/2026
1668  Amphetamine Aspartate Monohydrate, Amphetamine...     10/12/2022
1669  Lidocaine Hydrochloride Preservative Free, Inj...     02/22/2012

     shortage_end therapeutic_category source  \
0      04/29/2026       Cardiovascular    FDA
1      03/02/2026           Transplant    FDA
2      09/19/2025                Other    FDA
3      05/22/2026           Anesthesia    FDA
4      10/09/2025     Gastroenterology    FDA
...           ...                  ...    ...
1665   08/19/2025              Urology    FDA
1666   03/19/2026           Psychiatry    FDA
1667   01/27/2026       Cardiovascular    FDA
1668   06/02/2026           Psychiatry    FDA
1669   05/22/2026           Anesthesia    FDA

                                               raw_json  \
0     {"update_type": "Reverified", "initial_posting...
1     {"discontinued_date": "03/02/2026", "update_ty...
2     {"discontinued_date": "09/19/2025", "update_ty...
3     {"update_type": "Revised", "initial_posting_da...
4     {"discontinued_date": "10/09/2025", "update_ty...
...                                                 ...
1665  {"discontinued_date": "08/19/2025", "update_ty...
1666  {"discontinued_date": "03/19/2026", "update_ty...
1667  {"discontinued_date": "01/27/2026", "update_ty...
1668  {"update_type": "Revised", "initial_posting_da...
1669  {"update_type": "Reverified", "initial_posting...

                    ingested_at
0    2026-06-05 05:02:07.379150
1    2026-06-05 05:02:07.379204
2    2026-06-05 05:02:07.379250
3    2026-06-05 05:02:07.379286
4    2026-06-05 05:02:07.379322
...                         ...
1665 2026-06-05 05:02:07.410187
1666 2026-06-05 05:02:07.410200
1667 2026-06-05 05:02:07.410213
1668 2026-06-05 05:02:07.410228
1669 2026-06-05 05:02:07.410243

[1670 rows x 13 columns]

In [43]:
import inspect
print(inspect.getsource(normalize_fda))

def normalize_fda(records):
    rows = []
    for r in records:
        # therapeutic_category is a list — grab first item
        tc = r.get("therapeutic_category", [])
        category = tc[0] if isinstance(tc, list) and tc else str(tc) if tc else "UNCATEGORIZED"

        rows.append({
            "source_id":      r.get("id", ""),
            "drug_name":      r.get("generic_name", "").strip().upper() if r.get("generic_name") else "",
            "brand_name":     r.get("openfda", {}).get("brand_name", [""])[0],
            "manufacturer":   r.get("company_name", ""),
            "status":         r.get("status", "UNKNOWN").upper(),
            "reason":         r.get("shortage_reason", ""),       # ← fixed field name
            "presentation":   r.get("presentation", ""),
            "shortage_start": r.get("initial_posting_date", ""),  # ← actual date field
            "shortage_end":   r.get("update_date", ""),           # ← actual date field
            "therapeutic_category": category,                      # ← new field
            "source":         "FDA",
            "raw_json":       json.dumps(r),
            "ingested_at":    datetime.utcnow(),
        })
    return pd.DataFrame(rows)

In [44]:
df = normalize_fda(records)

print(df["status"].value_counts())

status
CURRENT               1144
TO BE DISCONTINUED     497
RESOLVED                29
Name: count, dtype: int64

In [45]:
# Check what the raw date field actually looks like
import json
sample = pd.read_sql("SELECT TOP 3 raw_json FROM staging.stg_fda_shortages", engine)
for row in sample["raw_json"]:
    r = json.loads(row)
    print("shortage_start_date:", r.get("initial_posting_date"))
    print("shortage_end_date:  ", r.get("update_date"))
    print("---")

shortage_start_date: 01/19/2023
shortage_end_date:   04/29/2026
---
shortage_start_date: 03/02/2026
shortage_end_date:   03/02/2026
---
shortage_start_date: 09/19/2025
shortage_end_date:   09/19/2025
---

In [46]:
# Check what fields the FDA API actually gives us
import json
sample = pd.read_sql("SELECT TOP 1 raw_json FROM staging.stg_fda_shortages", engine)
r = json.loads(sample["raw_json"][0])
print("ALL AVAILABLE FIELDS:")
for key, value in r.items():
    print(f"  {key}: {value}")

ALL AVAILABLE FIELDS:
  update_type: Reverified
  initial_posting_date: 01/19/2023
  package_ndc: 43547-411-09
  generic_name: Quinapril Hydrochloride Tablet
  contact_info: 866-931-9829
  availability: Unavailable
  related_info: Not available. Long-term backorder for all NDCs. No estimated release date at this time.
  openfda: {'application_number': ['ANDA205823'], 'brand_name': ['QUINAPRIL'], 'generic_name': ['QUINAPRIL'], 'manufacturer_name': ['Solco Healthcare US, LLC'], 'product_ndc': ['43547-411', '43547-410', '43547-412', '43547-413'], 'product_type': ['HUMAN PRESCRIPTION DRUG'], 'route': ['ORAL'], 'substance_name': ['QUINAPRIL HYDROCHLORIDE'], 'rxcui': ['312748', '312749', '312750', '314203'], 'spl_id': ['b8f1731a-cbac-4f64-a8d4-320b80b335e1'], 'spl_set_id': ['cd46691d-5593-4a9f-a937-999c6803e312'], 'package_ndc': ['43547-410-09', '43547-411-09', '43547-412-09', '43547-413-09'], 'unii': ['33067B3N2M']}
  update_date: 04/29/2026
  therapeutic_category: ['Cardiovascular']
  dosage_form: Tablet
  presentation: Quinapril Hydrochloride, Tablet, 10 mg (NDC 43547-411-09)
  company_name: Solco Healthcare US, LLC
  shortage_reason: Shortage of an active ingredient
  status: Current

In [47]:
df[["shortage_start","shortage_end",'therapeutic_category']].head()

  shortage_start shortage_end therapeutic_category
0     01/19/2023   04/29/2026       Cardiovascular
1     03/02/2026   03/02/2026           Transplant
2     09/19/2025   09/19/2025                Other
3     10/05/2022   05/22/2026           Anesthesia
4     10/09/2025   10/09/2025     Gastroenterology

In [48]:
print(df[["shortage_start", "shortage_end"]].head())

  shortage_start shortage_end
0     01/19/2023   04/29/2026
1     03/02/2026   03/02/2026
2     09/19/2025   09/19/2025
3     10/05/2022   05/22/2026
4     10/09/2025   10/09/2025

In [49]:
print(df["shortage_start"].isna().sum())
print(df["shortage_start"].head())

0
0    01/19/2023
1    03/02/2026
2    09/19/2025
3    10/05/2022
4    10/09/2025
Name: shortage_start, dtype: object

In [50]:
test = pd.to_datetime(df["shortage_start"], errors="coerce")
print("Valid dates:", test.notna().sum())
print("Null dates :", test.isna().sum())

Valid dates: 1670
Null dates : 0

In [51]:
df = normalize_fda(records)
print(df.columns.tolist())  # should show therapeutic_category
print(df["therapeutic_category"].value_counts().head(10))

['source_id', 'drug_name', 'brand_name', 'manufacturer', 'status', 'reason', 'presentation', 'shortage_start', 'shortage_end', 'therapeutic_category', 'source', 'raw_json', 'ingested_at']
therapeutic_category
Anesthesia                  338
Psychiatry                  242
Cardiovascular              196
Analgesia/Addiction         177
Endocrinology/Metabolism    169
Anti-Infective               99
Neurology                    97
Oncology                     84
Rheumatology                 52
Gastroenterology             48
Name: count, dtype: int64

In [52]:
pd.read_sql("""
    SELECT therapeutic_category, COUNT(*) as cnt
    FROM staging.stg_fda_shortages
    GROUP BY therapeutic_category
    ORDER BY cnt DESC
""", engine)

          therapeutic_category  cnt
0                   Anesthesia  338
1                   Psychiatry  242
2               Cardiovascular  196
3          Analgesia/Addiction  177
4     Endocrinology/Metabolism  169
5               Anti-Infective   99
6                    Neurology   97
7                     Oncology   84
8                 Rheumatology   52
9             Gastroenterology   48
10                  Hematology   27
11                       Other   26
12                 Dermatology   25
13           Pulmonary/Allergy   22
14                   Antiviral   19
15                  Transplant   11
16                       Renal    9
17               Ophthalmology    8
18             Medical Imaging    7
19                     Urology    5
20                Reproductive    4
21  Total Parenteral Nutrition    3
22                   Pediatric    2